// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Answer struct {
	ID         int64     `json:"id"`
	Text       string    `json:"text"`
	QuestionID int64     `json:"question_id"`
	IsCorrect  bool      `json:"is_correct"`
	CreatedAt  time.Time `json:"created_at"`
}

type Question struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	QuizID    int64     `json:"quiz_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Quiz struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Tag struct {
	ID   int64          `json:"id"`
	Name sql.NullString `json:"name"`
}

type TagsQuiz struct {
	TagsID    int64 `json:"tags_id"`
	QuizzesID int64 `json:"quizzes_id"`
}
